name: DeepGlycanSite
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.11=h7f8727e_2
  - pip=23.3=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.0.0
    - addict==2.4.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - anyio==4.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - ase==3.22.1
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - babel==2.13.1
    - beautifulsoup4==4.12.2
    - bezier==2023.7.28
    - bio==1.6.0
    - biopython==1.81
    - biothings-client==0.3.0
    - bleach==6.1.0
    - certifi==2023.7.22
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - comm==0.1.4
    - contextlib2==21.6.0
    - contourpy==1.1.1
    - coverage==7.4.0
    - cycler==0.12.1
    - cython==3.0.8
    - debugpy==1.8.0
    - decorator==5.1.1
    - deepspeed==0.5.9
    - defusedxml==0.7.1
    - dm-tree==0.1.8
    - einops==0.7.0
    - et-xmlfile==1.1.0
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - fair-esm==2.0.0
    - fasteners==0.19
    - fastjsonschema==2.18.1
    - filelock==3.13.1
    - fonttools==4.43.1
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.10.0
    - future==0.18.3
    - gprofiler-official==1.0.0
    - griddataformats==1.0.2
    - h5py==3.10.0
    - hjson==3.1.0
    - huggingface-hub==0.17.3
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.0
    - iniconfig==2.0.0
    - ipykernel==6.26.0
    - ipython==8.17.2
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.5.0
    - jupyter-console==6.6.3
    - jupyter-core==5.5.0
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.9.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.7
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.5
    - latexcodec==2.0.1
    - lightning-utilities==0.9.0
    - lmdb==1.4.1
    - markupsafe==2.1.3
    - matplotlib==3.8.1
    - matplotlib-inline==0.1.6
    - mdanalysis==2.6.1
    - mdciao==0.0.6
    - mdtraj==1.9.9
    - mistune==3.0.2
    - ml-collections==0.1.1
    - mmtf-python==1.1.3
    - mock==5.1.0
    - monty==2023.9.25
    - mpl-chord-diagram==0.4.1
    - mpmath==1.3.0
    - mrcfile==1.4.3
    - msgpack==1.0.7
    - multidict==6.0.4
    - mygene==3.2.2
    - natsort==8.4.0
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nose==1.3.7
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - numpy==1.26.1
    - omegaconf==2.3.0
    - openpyxl==3.1.2
    - overrides==7.4.0
    - packaging==23.2
    - palettable==3.3.3
    - pandas==2.1.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pillow==10.1.0
    - platformdirs==3.11.0
    - plotly==5.18.0
    - pluggy==1.3.0
    - pooch==1.8.0
    - prometheus-client==0.18.0
    - prompt-toolkit==3.0.39
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - py3dmol==2.0.4
    - pybtex==0.24.0
    - pycparser==2.21
    - pyg-lib==0.3.0+pt113cpu
    - pygments==2.16.1
    - pymatgen==2023.10.11
    - pyparsing==3.1.1
    - pytest==7.4.4
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-lightning==1.9.3
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - qtconsole==5.4.4
    - qtpy==2.4.1
    - rdkit==2023.9.1
    - referencing==0.30.2
    - regex==2023.10.3
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - ruamel-yaml==0.18.4
    - ruamel-yaml-clib==0.2.8
    - safetensors==0.4.0
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - seaborn==0.13.0
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - spglib==2.1.0
    - stack-data==0.6.3
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.3
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tokenizers==0.14.1
    - tomli==2.0.1
    - torch==1.13.1+cpu
    - torch-cluster==1.6.3
    - torch-geometric==2.4.0
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torch-spline-conv==1.2.2+pt113cpu
    - torchaudio==0.13.1+cpu
    - torchmetrics==1.2.0
    - torchvision==0.14.1+cpu
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.13.0
    - transformers==4.34.1
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - uncertainties==3.1.7
    - uri-template==1.3.0
    - urllib3==2.0.7
    - wcwidth==0.2.9
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - widgetsnbextension==4.0.9
    - xlsxwriter==3.1.9
    - yarl==1.9.2
    - zipp==3.17.0
prefix: /work/home/xinheng/.conda/envs/DeepGlycanSite
